Create zh_cn.json
CoolMineman/BitsAndChisels pull request #4
Opened 2020-11-24 12:42 UTC by qsefthuopq

2020-11-24 23:06 UTC, LeoCTH approved these changes

2020-11-25 00:44 UTC, Neubulae requested changes

2020-11-25 00:44 UTC, Neubulae commented on src/main/resources/assets/bitsandchisels/lang/zh_cn.json
> +    "item.bitsandchisels.bit_item": "%s碎屑",
are `bits` supposed to be dust/remnant/broken parts? maybe 小块 fits better?

2020-11-25 02:25 UTC, qsefthuopq commented on src/main/resources/assets/bitsandchisels/lang/zh_cn.json
> +    "item.bitsandchisels.bit_item": "%s碎屑",
原C & B的翻译就是碎屑
我觉得小块不通顺
在游戏内显示为草方块小块

2020-11-25 04:14 UTC, merged

2020-11-25 04:49 UTC, Neubulae commented on src/main/resources/assets/bitsandchisels/lang/zh_cn.json
> +    "item.bitsandchisels.bit_item": "%s碎屑",
没觉得不通顺